[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertCharPre'
on_i = 1
on_ft = 'snippet'
depends = ['neosnippet-snippets', 'context_filetype']
hook_source = '''
source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_event = 'InsertCharPre'
hook_source = '''
source ~/.config/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

